- name: install BIND packages
  yum: name={{ bind_packages }} state=latest
  notify: restart named

- name: configure BIND
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
  notify: restart named

- name: add zone file for osedemo.internal
  template:
    src: osedemo.internal.zone.j2
    dest: /var/named/osedemo.internal.zone
    owner: root
    group: named
    mode: 0644
  notify: restart named

- name: add reverse zone file for osedemo.internal
  template:
    src: osedemo.internal.rr.zone.j2
    dest: /var/named/osedemo.internal.rr.zone
    owner: root
    group: named
    mode: 0644
  notify: restart named

- name: add zone file for osedemo.example.com
  template:
    src: osedemo.example.com.zone.j2
    dest: /var/named/osedemo.example.com.zone
    owner: root
    group: named
    mode: 0644
  notify: restart named

- name: start and enable named service
  service: name=named enabled=yes state=started
