- name: configure eth0
  copy:
    src: ifcfg-eth0
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: 0644
  notify:
    - restart network
    - restart NetworkManager

- name: configure hostname
  copy:
    content: |
      {{ ansible_hostname }}.osedemo.internal
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  notify:
    - restart network
    - restart NetworkManager

- name: configure dhclient
  template:
    src: dhclient.conf.j2
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart network
    - restart NetworkManager
