- name: register system to RHN
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"

- name: attach subscription
  shell: >
    subscription-manager attach --pool {{ rhn_pool_id }}
    && touch /root/subscribed-{{ rhn_pool_id }}
  args:
    creates: /root/subscribed-{{ rhn_pool_id }}

- name: disable all repos
  shell: >
    subscription-manager repos --disable=*
    && touch /root/disabled_default_repos
  args:
    creates: /root/disabled_default_repos

- name: enable RHEL repo
  shell: >
    subscription-manager repos --enable=rhel-7-server-rpms
    && touch /root/enabled_rhel-7-server-rpms
  args:
    creates: /root/enabled_rhel-7-server-rpms

- name: update RHEL
  yum: name=* state=latest
  notify:
    - reboot
    - wait for host to reboot
