# This ensures that DNS works, since images may be configured to use an
# internal DNS service.
- name: use public DNS
  copy:
    dest: "/etc/resolv.conf"
    content: |
      search default
      nameserver 8.8.8.8
      nameserver 8.8.4.4

- name: register system to RHN
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"

- name: attach subscription
  command: subscription-manager attach --pool {{ rhn_pool_id }}

- name: disable all repos
  command: subscription-manager repos --disable=*

- name: enable RHEL repo
  command: subscription-manager repos --enable=rhel-7-server-rpms

- name: update RHEL
  yum: name=* state=latest
  notify:
    - reboot

- name: wait for host to reboot
  local_action: wait_for host={{ inventory_hostname }} state=started
  sudo: false
