- name: reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  notify:
    - wait for host to reboot

- name: wait for host to reboot
  local_action: wait_for host={{ inventory_hostname }} state=started
  sudo: false
