- hosts: all
  name: gather facts about other hosts
  tasks: []

- hosts: dns
  name: setup DNS server
  roles:
    - dns-server

  tasks:

    - name: configure BIND
      template:
        src: templates/dns-server/named.conf.j2
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640
      notify: restart named

    - name: add zone file for osedemo.internal
      template:
        src: templates/dns-server/osedemo.internal.zone.j2
        dest: /var/named/osedemo.internal.zone
        owner: root
        group: named
        mode: 0644
      notify: restart named

    - name: add reverse zone file for osedemo.internal
      template:
        src: templates/dns-server/osedemo.internal.rr.zone.j2
        dest: /var/named/osedemo.internal.rr.zone
        owner: root
        group: named
        mode: 0644
      notify: restart named

    - name: add zone file for osedemo.example.com
      template:
        src: templates/dns-server/osedemo.example.com.zone.j2
        dest: /var/named/osedemo.example.com.zone
        owner: root
        group: named
        mode: 0644
      notify: restart named

  handlers:
    - name: restart named
      service: name=named state=restarted
